### ISSUE TITLE
Template tag error thrown on missing 'not_agreed_terms'

### ISSUE THREAD

**Issue by kutenai** [cyface/django-termsandconditions#104]
I've been trying to get a clean lot output, but I see this in my debug logs
```
2019-08-11 13:19:47,896 django.channels.server DEBUG    Daphne running, listening on 127.0.0.1:8000
2019-08-11 13:30:05,301 django.template DEBUG    Exception while resolving variable 'not_agreed_terms' in template 'home/home_page.html'.
Traceback (most recent call last):
  File "/Volumes/sharpertool/proj/gardentronic/gardentronic/.venv3/lib/python3.7/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "/Volumes/sharpertool/proj/gardentronic/gardentronic/.venv3/lib/python3.7/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'not_agreed_terms'

During handling of the above exception, another exception occurred:

* THIS GOES ON FOR A LONG TIME *
```

It drove me crazy for a while, but I finally tracked it down to this the inclusion tag "show_terms_if_not_agreed"

The tag has this logic
```
    if not_agreed_terms and is_path_protected(url.path):
        return {'not_agreed_terms': not_agreed_terms, 'returnTo': url.path}
    else:
        return {}
```
The problem is that it returns without the value set for 'not_agreed_terms', and so that means that the snippet, which includes this:
```
{% if not_agreed_terms %}
    {% render_bundle 'terms_modal' 'css' 'ASSETS' %}
```
Will raise a template Exception unless the user has NOT agreed to terms, basically, all of the time.

* SUGGESTION *
Return the value set to "False", -- it's inverted logic, but it works..
```
    if not_agreed_terms and is_path_protected(url.path):
        return {'not_agreed_terms': not_agreed_terms, 'returnTo': url.path}
    else:
        return {'not_agreed_terms': False}
```

This cleans up the error logs, and it's a cleaner solution anyway. Oh, and it likely improves performance since the Django stack does not need to unwind a bunch of stack frames.

**Comment by cyface** [comment]
Sounds good, thanks for the PR!
