### ISSUE TITLE
Problems when installing on a new venv

### ISSUE THREAD

**Issue by goromachine** [cyface/django-termsandconditions#163]
I'm trying to install the package to another computer which is using the same packages as the first one I got it installed and I'm having an error.

Information of the system:
Python 3.6
Django 2.2
PostgreSQL 12

The error:

```
Collecting django-termsandconditions==2.0.6
  Using cached django-termsandconditions-2.0.6.tar.gz (22 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

DEPRECATION: The -b/--build/--build-dir/--build-directory option is deprecated. pip 20.3 will remove support for this functionality. A possible replacement is use the TMPDIR/TEMP/TMP environment variable, possibly combined with --no-clean. You can find discussion regarding this at https://github.com/pypa/pip/issues/8333.
  ERROR: Command errored out with exit status 1:
   command: /Users/juanjo/PycharmProjects/ekiterplatform/venv/bin/python /Users/juanjo/PycharmProjects/ekiterplatform/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/lh/5bwwxr2911z513712wt71l_80000gn/T/tmpdy3s1mne
       cwd: /private/var/folders/lh/5bwwxr2911z513712wt71l_80000gn/T/pycharm-packaging/django-termsandconditions
  Complete output (10 lines):
  Traceback (most recent call last):
    File "/Users/juanjo/PycharmProjects/ekiterplatform/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/Users/juanjo/PycharmProjects/ekiterplatform/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/juanjo/PycharmProjects/ekiterplatform/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 108, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/Users/juanjo/PycharmProjects/ekiterplatform/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 99, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/juanjo/PycharmProjects/ekiterplatform/venv/bin/python /Users/juanjo/PycharmProjects/ekiterplatform/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/lh/5bwwxr2911z513712wt71l_80000gn/T/tmpdy3s1mne Check the logs for full command output.
```

If I try to uninstall and reinstall the package on the other computer it works just fine.

If you need any extra information please ask for it. Thank you

**Comment by cyface** [comment]
Hey there - looks like the your _system_ version of setuptools might be old - take a look at this thread: https://github.com/pypa/setuptools/issues/1694

**Comment by goromachine** [comment]
I'm on my last version of setuptools==49.6.0, the last version of pip==20.2.2 and they say this happens when, among other conditions, 'setuptools is less than 40.8.0.'.

I tried downgrading pip with: pip install --upgrade pip==19.0 - As [told here](https://github.com/pypa/pip/issues/6264#issuecomment-572896391)

And now is working.

Thank you for referencing that thread.
